### ISSUE TITLE
Dockerization (and CLI-fication)

### ISSUE THREAD

**Issue by djechelon** [bhafer/TitaniumBackupDecrypt#8]
Hi,

I would be enthusiast to contribute to this utility. I am a former PHP developer with some free time during this pandemic.

While I am rusty in PHP, I could try to help with my Docker experience. Basically, my request is to transform this utility into a full CLI utility that can be invoked from Docker, basically because I don't like (no... I HATE) to install yet another programming runtime on my personal rig. I started to love containers when I discovered that apps don't make conflicts each other and stay tidy.

I will try to dockerize the app locally, but briefly looking at the project it looks like it asks for a password prompt. I think it's worth to make some changes in PHP code so that the application takes the password as an argument. After all, one should be running this utility from a local device.

Let me see what I can try to do

**Comment by bhafer** [comment]
Great! Thanks for your interest. I would be happy to collaborate. This project is still working stably with latest version of TiB. No changes have been required in a long while.

Initially, I wanted to avoid the user having to provide the password in a plaintext argument. Thus the logic for its current form:
Usage:     php TitaniumBackupDecrypt <archive-file>

But I could easily add a second invocation signature that accepted two arguments:
Usage:     php TitaniumBackupDecrypt <archive-file> <password>

Would that be what you needed to get started?

**Comment by djechelon** [comment]
Hi, I just forked the project. I'll start hacking soon.

There are additional options and I would like to encourage you to embrace both

# Argument number

Of course `php TitaniumBackupDecrypt <archive> <password>` is great. Basically the utility will count the arguments.

- If args.length == 0, display some help text
- else if args[1] is undefined assume only archive and prompt
- else if args[1] != null use arg[1] as password

# The environment

In the Docker world, secrets are often exchanged via environment variables. You could use as an alternate to retrieve the password from invocation

```
//Please note it's pseudocode
var password = null;
if (defined(args[1]))
    password = args[1];
else if (defined(env['TB_ARCHIVE_PASSWORD']))
    password = env['TB_ARCHIVE_PASSWORD']
else 
    password = stdin.readLine();
```

This makes everything backwards compatible

**Comment by djechelon** [comment]
I'll start to create my first version of the Dockerfile

I expect the invocation to be `docker run --rm -v <archive>:/<archive> --e TB_ARCHIVE_PASSWORD=<password> bhafer/TitaniumBackupDecrypt <archive>`

Need to find a good php image

**Comment by djechelon** [comment]
As you can see I have posted my PR. I did only the Docker thing. Thanks to your tool I was able to decrypt a file that I had locked with TB.

Didn't do the CLI-fication thing as looks like Docker is sufficient to handle the password prompt. Of course the image is only local

**Comment by bhafer** [comment]
Thanks for your contribution, djechelon. You can see that I have also added support for the three modes of password parameter passing in the new tag 1.2.0 version:

```
Usage:
     php TitaniumBackupDecrypt <archive-file>
          Will check for TB_ARCHIVE_PASSWORD environment variable or else prompt for password.
            --OR--
     php TitaniumBackupDecrypt <archive-file> <password> 
```

**Comment by djechelon** [comment]
Wunderbar! If you need help pushing the image to Hub, or if you just like to give it a try, drop me a message

**Comment by bhafer** [comment]
(I did not get a notification for your reply. :( )

> If you need help pushing the image to Hub, or if you just like to give it a try, drop me a message

I merged your pull request and released v1.2.0.

I'm not sure what you are referring to about Hub?

**Comment by djechelon** [comment]
Hub = hub.docker.com, official image catalog of Docker

**Comment by djechelon** [comment]
Here are instructions on how to setup bhafer/TitaniumBackupDecrypt on Docker Hub.

1. Sign up to Hub

https://hub.docker.com is the place to be

Make sure you link your GitHub account, because it matters

2. Create a repository

This is the djechelon example

https://hub.docker.com/repository/create

![Create a repository](https://user-images.githubusercontent.com/3042285/101820808-65a4e200-3b27-11eb-9ee5-730c7d9d7194.png)

Make sure the Hub repository is public

Choose your GitHub repository

![Build settings](https://user-images.githubusercontent.com/3042285/101820953-8ec57280-3b27-11eb-91ec-abc7c0673e29.png)

3. Create and build

Docker will use the Dockerfile I have committed for you to build an image. Since we used the "Create and build" button, Hub will also build the image using their pipeline. This will take minutes because of the long queue.

Make sure that Hub builds the image successfully.

The URL **should** be https://hub.docker.com/repository/registry-1.docker.io/bhafer/titanium-backup-decrypt/builds

4. Pull from Docker

From terminal run

`$ docker pull bhafer/titanium-backup-decrypt`

5. Enjoy

Try `docker pull bhafer/titanium-backup-decrypt`

![Docker pull](https://user-images.githubusercontent.com/3042285/101824666-d3074180-3b2c-11eb-84b3-a491fe1d3ae7.png)
